### ISSUE TITLE
Support graphql 15?

### ISSUE THREAD

**Issue by alex-knyazev** [robrichard/graphql-fields#36]
I use this lib in my project and I want to move to graphql 15. 

Can you set graphql as peer dependency and include 15?

**Comment by robrichard** [comment]
Does it not work with graphql 15? There's no peer dependency in this package at all. It should work unless there was a breaking change that affected something here.

**Comment by alex-knyazev** [comment]
@robrichard
I didn't check but I'm sure it will work.

But if your package.json have graphql v ^14 but my have v 15 - npm will install both.

So if other grapql libraries set graphql as peer dependency

**Comment by robrichard** [comment]
The package.json here does not have graphql v14 set as a dependency.

**Comment by alex-knyazev** [comment]
Sorry, I was mistaken
