### ISSUE TITLE
Convert JSON back to Query Language?

### ISSUE THREAD

**Issue by jasonbahl** [robrichard/graphql-fields#4]
Do you know of any way to convert these fields back to the Query Language?

For example, you say this will return: 

```
{
  "profile": {
    "firstName": {},
    "lastName": {},
    "middleName": {}
  },
  "email": {},
  "id": {}
```

Instead of sending the fields to a REST server, I want to send them to another GraphQL server, so I'd want that in the "query language" format, like: 

```
{ 
     profile { 
          firstName, 
          lastName, 
          middleName 
     }, 
     email, 
     id 
}
```

**Comment by robrichard** [comment]
I think you could do it by recursively iterating over each objects properties and building up a string. You would lose any information about arguments, directives, etc.

Anyway, I think this is out of the scope of this package.

**Comment by wesbos** [comment]
Has anyone done this? Would be a nice option or additional method to add
