### ISSUE TITLE
End leafs are object literal

### ISSUE THREAD

**Issue by furkanedu** [robrichard/graphql-fields#5]
`const projection = graphqlFields( fourth )`

What I get from this is :

```
{
  key1 : {},
  key2 : {
   key2_1 : {},
   key2_2 : {}
 }
}
```

instead I want the empty objects as 1, since mongo doesn t like it.  Like this : 

```
{
  key1 : 1,
  key2 : {
   key2_1 : 1,
   key2_2 : 1
 }
}
```

So that I was trying to write a function to convert empty objects to 1s. But I think there should be a configuration to make this possible. Thanks.

**Comment by mormahr** [comment]
I would not consider this to be the responsibility of this library. It has nothing to do with the specifics of mongodb.

And a conversion function could be as simple as

```js
function convert(obj) {
    if (typeof obj !== "object") {
        // "ignore" non object values
        return obj
    }
    
    const keys = Object.keys(obj)
    if (keys.length > 0) {
        // copy all properties over while converting them
        const clone = {}
        for (const key of keys) {
            clone[key] = convert(obj[key])
        }
        return clone
    } else {
        return 1
    }
}
```
_no guarantees, of course_

**Comment by robrichard** [comment]
Yes I agree with @mormahr. You can easily check if it's a leaf node by using Object.keys

**Comment by furkanedu** [comment]
Since there is no specific reason for end leafs to be empty object, it could be handful if possible. Anway I already stopped using this library, because of other problems related to mongodb. Thanks for your answers and time.
